Компонент карточки блога
3orger/react-purpleschool pull request #1
Opened 2023-08-30 17:53 UTC by 3orger

2023-09-03 08:30 UTC, Grinv requested changes

2023-09-03 08:30 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +        src="/post.png"
Лучше импортировать картинки и затем передавать в Image. Так кеширование лучше работает и next сразу при билде создаёт все варианты на основе нашего конфига.
```jsx
import postImage from '@/public/images/post.png';
return <Image src={postImage} />

2023-09-03 08:30 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +        src="/post.png"
Советую в public всё-таки создавать подкатегории, чтоб не было свалки)
`/public/icons`
`/public/images`
`/public/pdf`

2023-09-03 08:30 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +    <div className="card-post">
Для карточек лучше использовать тег `article`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article
>Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.

2023-09-03 08:30 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +import Heading from '../Heading/Heading';
Не ошибка, но как рекомендация. Я бы прописывал путь не как `../Heading/Heading`, а как `@/components/Heading/Heading`
Ибо тут под урлу сразу понимаешь, что это за сущность, что это компонент.
Пока импортов мало - это ок. Но в будущем будешь импортировать сущности разных видов, например
`@/api/...`, `@/utils/...`, `@/helpers/...`, `@/hooks/...`, `@/types/...`. Вот тогда можно уже будет запутаться)

2023-09-03 08:30 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +          <a className="card-post__category" href="#">
Для ссылок используем компонент `next/link`

2023-09-03 08:30 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +        <a
Используем `next/link`

2023-09-03 08:30 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +      <div className="card-post__bottom">
Можно использовать тэг `footer`

2023-09-03 08:30 UTC, Grinv commented on app/components/Like/Like.tsx
> +      <button className={styles.like__btn} type="button">
Я бы весь компонент обернул в button. И счётчик бы в кнопку захватил. Чтоб кликабельная область была больше. Кликабельная область больше -> С мобилки пальцем попасть проще -> больше кликов -> маркетологи рады)

2023-09-03 08:30 UTC, Grinv commented on app/page.tsx
> +      {/* <div className={styles.description}>
Комментарии и мусор в PR не оставляем

2023-09-03 08:30 UTC, Grinv commented on package.json
>      "@types/react-dom": "18.2.7",
Всё, что у нас работает/используется в продакшене - в dependencies.
Всё что нам требуется для разработки, сборки, деплоя, проверки, транспилинга - в devDependencies
Соответственно, все `@types/`, `eslint...`, `typescript` должны храниться в devDependencies.
Я знаю, что next.js по умолчанию ставит их в dependencies, но это их косяк)

2023-09-03 08:30 UTC, Grinv commented on app/page.tsx
> +import CardPost from './components/CardPost/CardPost';
Сделай лучше алиасы, чтоб могли обращаться к компонентам откуда угодно через `@/components/...`
Тоже самое про public (`@/public/...`)

2023-09-03 08:30 UTC, Grinv commented on app/layout.tsx
> +  subsets: ['cyrillic'],
Если будет использовать английский, не забудь потом сюда добавить `latin`. Но это опять же, только если будет использоваться)

2023-09-03 08:30 UTC, Grinv commented on app/layout.tsx
>  export default function RootLayout({ children }: { children: React.ReactNode }) {
Лучше типы прописывать отдельно. Так они не миксуются с пропсами и читать проще и удобнее
```jsx
interface Props {
   children: React.ReactNode
}

export default function RootLayout({ children }: Props) {

2023-09-03 08:30 UTC, Grinv commented on app/layout.tsx
> +      <body className={openSans.className}>{children}</body>
Советую шрифты применять через css переменные. Так более гибко получается.
Как сделать - можно посмотреть тут: https://nextjs.org/docs/app/api-reference/components/font#css-variables

2023-09-03 08:30 UTC, Grinv commented
![Screenshot 2023-09-03 at 16 30 25](https://github.com/3orger/react-purpleschool/assets/4070730/59f126cb-b1e2-4fd5-911c-e74d6af6c295)
Не забудь нажать на кнопку Load more..., там ещё комментарии)

2023-09-04 18:16 UTC, 3orger commented on app/components/CardPost/CardPost.tsx
> +        src="/post.png"
хм..а если у нас картинок 10-20 есть какой-то способ не импортировать их таким образом, а то тоже не красиво будет.

2023-09-04 18:17 UTC, 3orger commented on app/components/CardPost/CardPost.tsx
> +        src="/post.png"
Поправил. Спасибо

2023-09-04 18:17 UTC, 3orger commented on app/components/CardPost/CardPost.tsx
> +    <div className="card-post">
Поправил. Спасибо

2023-09-04 18:17 UTC, 3orger commented on app/components/CardPost/CardPost.tsx
> +import Heading from '../Heading/Heading';
Поправил. Спасибо

2023-09-04 18:17 UTC, 3orger commented on app/components/CardPost/CardPost.tsx
> +          <a className="card-post__category" href="#">
Поправил. Спасибо

2023-09-04 18:17 UTC, 3orger commented on app/components/CardPost/CardPost.tsx
> +        <a
Поправил. Спасибо

2023-09-04 18:17 UTC, 3orger commented on app/components/CardPost/CardPost.tsx
> +      <div className="card-post__bottom">
Поправил. Спасибо

2023-09-04 18:17 UTC, 3orger commented on app/components/Like/Like.tsx
> +      <button className={styles.like__btn} type="button">
Поправил. Спасибо

2023-09-04 18:17 UTC, 3orger commented on app/page.tsx
> +      {/* <div className={styles.description}>
Поправил. Спасибо

2023-09-04 18:18 UTC, 3orger commented on package.json
>      "@types/react-dom": "18.2.7",
Поправил. Спасибо

2023-09-04 18:18 UTC, 3orger commented on app/page.tsx
> +import CardPost from './components/CardPost/CardPost';
Поправил. Спасибо

2023-09-04 18:18 UTC, 3orger commented on app/layout.tsx
> +  subsets: ['cyrillic'],
Добавлю. Сейчас просто нету en. )

2023-09-04 18:18 UTC, 3orger commented on app/layout.tsx
>  export default function RootLayout({ children }: { children: React.ReactNode }) {
Да...упустил. Согласен. Мне не понравилось как видео показывали, что пропсы вообще в отдельном файле и т.п...не удобно как по мне жутко :)

2023-09-04 18:19 UTC, 3orger commented on app/layout.tsx
> +      <body className={openSans.className}>{children}</body>
Вроде сделал)

2023-09-08 06:40 UTC, Grinv approved these changes

2023-09-08 06:40 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +      />
Опять же, если не уверен, что у тебя всегда будут приходить картинки правильного aspect-ratio - лучше подстаховаться и сделать, как советует сам next
https://nextjs.org/docs/pages/api-reference/components/image#responsive-image-with-fill

2023-09-08 06:40 UTC, Grinv commented on app/components/CardPost/CardPost.tsx
> +        <a className="card-post__more" href="#">
`next/link`

2023-09-08 06:40 UTC, merged